### ISSUE TITLE
UniqueProcessIDOffset

### ISSUE THREAD

**Issue by plowsec** [can1357/physical_mem_controller#5]
Hey,

First of all, thanks for your work, it's really awesome!

I've tried to use it and besides the usual small fixes for older code base, I have one bug for which I don't have enough knowledge to fix :P

![image](https://user-images.githubusercontent.com/13260466/131977541-981f3c70-bf8a-433c-9b7b-32d7dc6cd23f.png)

Here the first assertion fails, because 
```
	if ( !Controller.UniqueProcessIdOffset )
		Controller.CreationStatus = 1;
```

Is that this part that should be fixed ? https://github.com/can1357/physical_mem_controller/blob/master/MemoryController.h#L437

In fact, I don't know if you're still using this tool and if it is still supposed to work well :)

Tested on Windows 10 20H2 build 19042

**Comment by can1357** [comment]
Hey there, swap the < 0x400 there with < 0x800 and it should work. Bit of an old code base, not too well written haha.
